language: ruby
# bundler_args: --without development
script:
  - 'bundle exec rake build'
  - 'bundle exec rake rspec'
rvm:
  - 2.0
  - 2.1
gemfile:
  - Gemfile
branches:
  only:
    - master
    - develop
